gui:
  border: bold
  animateExplosion: false
  filterMode: fuzzy
  statusPanelView: allBranchesLog
git:
  allBranchesLogCmds:
    - git log --graph --all --color=always --pretty=format:'%C(magenta)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
disableStartupPopups: true
